install.packages("forecast")
library(forecast)
library("forecast")
regall <- lm(Sales ~ Radio+TV+Newspaper, data=mydata)
regt <- lm(Sales ~ TV, data=mydata)
regrn <- lm(Sales ~ Radio+Newspaper, data=mydata)
regn <- lm(Sales~Newspaper, data=mydata)
regr <- lm(Sales~Radio, data=mydata)
regtn <- lm(Sales~TV+Newspaper, data=mydata)
regtr<- lm(Sales~TV+Radio, data=mydata)
CV(regall)
CV(regt)
CV(regrn)
CV(regn)
CV(regr)
CV(regtn)
CV(regtr)
#the model that minimizes AIC and BIC and CV is the Sales ~ TV+Radio equation
install.packages("glmnet")
library(glmnet)
x = model.matrix(Sales~.,mydata)
y=mydata$Sales
LASSOreg=cv.glmnet(x,y,alpha=1)
summary(LASSOreg)
predict(LASSOreg, type="coefficients")
